# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pathfinder 2 Wiki
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenue sur le prototype de wiki pour pathfinder 2.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

plugins:
  - jekyll-relative-links
  - jekyll-toc

collections:
  dons:
    output: true
    category: ['don']
  ascendances:
    output: true
    category: ['ascendance']
  backgrounds:
    output: true
    category: ['background']
  classes:
    output: true
    category: ['classe']
  pretires:
    output: true
    category: ['prétiré']
  donsascendance:
    output: true
    category: ["don d'ascendance"]
  donsclasse:
    output: true
    category: ['don de classe']
  donsarchetype:
    output: true
    category: ["don d'archétype"]
  conditions:
    output: true
    category: ['condition']
  traits:
    output: true
    category: ['trait']
  objetsalchimiques:
    output: true
    category: ['objet alchimique']
  objetsmagiques:
    output: true
    category: ['objet magique']
  objetsspeciaux:
    output: true
    category: ['objet spécial']
  runes:
    output: true
    category: ['rune']
  trappes:
    output: true
    category: ['trappe']
  sorts:
    output: true
    category: ['sort']
  rituels:
    output: true
    category: ['rituel']


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .vscode/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"